// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqmbatqakftemqiojkgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxbWJhdHFha2Z0ZW1xaW9qa2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3OTQ4NTgsImV4cCI6MjA2NTM3MDg1OH0.YGAQxW4NYZYN4ruxMEtptxo31By9ivSQrDwa7YfyiwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);